services:
  db:
    image: postgres
    volumes:
      - ./db/database_structure.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    env_file: "default.env"

  dynamodb:
    image: amazon/dynamodb-local

  ticket-api:
    image: ticket-api
    env_file: "default.env"
    ports:
      - 3000:3000

volumes:
  pgdata: