services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - dynamodata:/home/dynamodblocal/data

  ticket-api:
    image: ticket-api
    env_file: "default.env"
    ports:
      - 3000:3000

volumes:
  dynamodata: